---
- name: 'synthing - add repo keys'
  apt_key:
    url: 'https://syncthing.net/release-key.txt'
    state: 'present'

- name: 'syncthing - add repos'
  apt_repository:
    repo: 'deb https://apt.syncthing.net/ syncthing stable'
    state: 'present'
    update_cache: true

- name: 'syncthing - manage package'
  package:
    name: 'syncthing'
    state: 'latest'
