---
nvtk_sys_packages_common:
  - acpid
  - chrony
  - curl
  - dos2unix
  - dstat
  - ethtool
  - fio
  - fping
  - htop
  - inxi
  - iotop
  - iperf
  - iptraf
  - jq
  - links
  - lnav
  - lvm2
  - mc
  - mtr
  - multitail
  - ncdu
  - ncftp
  - nmap
  - p7zip
  - parallel
  - partclone
  - parted
  - pbzip2
  - psmisc
  - python-jmespath
  - python-pip
  - python-simplejson
  - python-virtualenv
  - rsync
  - screen
  - smartmontools
  - stress-ng
  - sudo
  - tmux
  - unzip
  - virt-what
  - wget
