# install packages for ubuntu desktop
# used very very rarely, mainly fo ether hosts.
---
- name: 'Prepare desktop system'
  hosts: 127.0.0.1
  connection: local
  become: true
  gather_facts: true
  # workaround for 'please install python3-apt' when running in pyenv/virtualenv
  # yet, still even localhost requires python3-apt package installed
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: 'Remove certain repos'
      apt_repository:
        repo: 'ppa:jonls/redshift-ppa'
        state: 'absent'
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: 'Update APT'
      apt:
        autoclean: true
        autoremove: true
        cache_valid_time: 0
        update_cache: true
        install_recommends: false
      when: ansible_os_family == 'Debian'
  roles:
    - nvtk-users
    - nvtk-rsyslog
    - nvtk-git
    - nvtk-sys-core
    - nvtk-desktop
    - nvtk-syncthing
    - nvtk-doublecmd
    - nvtk-hugin
    - geerlingguy.docker
