# install packages for ubuntu desktop
# used very very rarely, mainly fo ether hosts.
---
- name: 'Prepare desktop system'
  hosts: 127.0.0.1
  connection: local
  become: true
  gather_facts: true
  # workaround for 'please install python3-apt' when running in pyenv/virtualenv
  # yet, still even localhost requires python3-apt package installed
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: 'Update APT'
      apt:
        autoclean: true
        autoremove: true
        cache_valid_time: 0
        update_cache: true
        install_recommends: false
      when: ansible_os_family == 'Debian'
  roles:
    - nvtk_users
    - nvtk_rsyslog
    - nvtk_git
    - nvtk_sys_core
    - nvtk_desktop
    - nvtk_syncthing
    - nvtk_doublecmd
    - nvtk_hugin
    - nvtk_qbittorrent
    - geerlingguy.docker
    - markosamuli.gcloud
    - andrewrothstein.kubectl
    - chaosmail.sublime-text
