# this is ansible-galaxy dependencies files
# use it as:
# ansible-galaxy install -r requirements.yml

---
- src: geerlingguy.docker
  version: 2.5.2
- src: devoperate.gcloud
  version: v0.1.0
- src: andrewrothstein.kubectl
  version: v1.1.19
- src: chaosmail.sublime-text
  version: master
