# this is ansible-galaxy dependencies files
# use it as:
# ansible-galaxy install -r requirements.yml

---
- src: geerlingguy.docker
  version: 2.9.0
- src: markosamuli.gcloud
  version: v2.1.2
- src: andrewrothstein.kubectl
  version: v1.1.49
- src: chaosmail.sublime-text
  version: master
