---
- name: 'Load a variable file based on the OS type'
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "main.yml"

- name: 'Add user kaszpir'
  user:
    append: true
    create_home: true
    force: true
    generate_ssh_key: false
    groups:
      - '{{ sudo_group }}'
    name: 'kaszpir'
    # yamllint disable-line
    password: '$6$GzFUQKeT$UqM5wEjxrCrHJGhfY6DZ.ro2s772Yhg99jjBS3GqlS8Ww8nXFPlzZsmjtvM7so7wM1q2zWtgbgUWrCP5YTaPT1'
    shell: '/bin/bash'
    state: 'present'

- name: 'Add SSH pub key to root - kaszpir@bagno'
  authorized_key:
    user: 'root'
    # yamllint disable-line
    key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAEe0HIh54Qrb/1oVa7qeG2zglEXl+vryHgi8Dad95hlYROxfjTnG5FDt9RX3cT6SvFjZ34+/L995Tq3O8v3eh87KgRcfU/tXpBu+dKAX/6xVQDprNmDsUNWH+/RGwBFj/rlkiyciop3JtPs7Pgec/bzmcbtETj1OiHHNw2uKMHznf00hMxbCBQ4hb15TZjCRYalgDO77oXMjrygUqb1k2If+vo4MZ6KapYGnaCwes/qJoxBzWTl8TGtAPQc0hU8hCQT9Eh7vWVx6mP48cgj6VKfHas97sd86dbv8AqCYNqBQ8Ai4721+FqPsxaJHn6E755OEFBgyPcTqpSbacxOnZ kaszpir@bagno'  # noqa 204
    state: 'present'

- name: 'Add SSH pub key to kaszpir - kaszpir@bagno'
  authorized_key:
    user: 'kaszpir'
    # yamllint disable-line
    key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAEe0HIh54Qrb/1oVa7qeG2zglEXl+vryHgi8Dad95hlYROxfjTnG5FDt9RX3cT6SvFjZ34+/L995Tq3O8v3eh87KgRcfU/tXpBu+dKAX/6xVQDprNmDsUNWH+/RGwBFj/rlkiyciop3JtPs7Pgec/bzmcbtETj1OiHHNw2uKMHznf00hMxbCBQ4hb15TZjCRYalgDO77oXMjrygUqb1k2If+vo4MZ6KapYGnaCwes/qJoxBzWTl8TGtAPQc0hU8hCQT9Eh7vWVx6mP48cgj6VKfHas97sd86dbv8AqCYNqBQ8Ai4721+FqPsxaJHn6E755OEFBgyPcTqpSbacxOnZ kaszpir@bagno'  # noqa 204
    state: 'present'
