---
- name: 'Remove retarded packages - Debian family'
  apt:
    name:
      - btrfs-tools
      - juju
      - juju-core
      - landscape-client
      - landscape-common
      - ntp
      - ntpd
      - popularity-contest
      - ufw
      - ubuntu-advantage-tools
    state: 'absent'
  when: ansible_os_family == 'Debian'

- name: 'Remove retarded packages - RedHat family'
  yum:
    name:
      - ntp
      - ntpd
    state: 'absent'
  when: ansible_os_family == 'RedHat'

- name: 'Remove packages on virtual machines - Debian family'
  apt:
    name:
      - smartmontools
      - hdparm
    state: 'absent'
  when:
    - ansible_os_family == 'Debian'
    - ansible_virtualization_role == 'guest'
