---

- name: 'Load a variable file based on the OS type'
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- include_tasks: 'sysctl.yml'
- include_tasks: 'setup.yml'
- include_tasks: 'lvm.yml'
- include_tasks: 'cleanup.yml'
