---
- name: 'Install core packages'
  package:
    name: '{{ packages_desktop }}'
    state: 'latest'

- name: 'Remove specific desktop packages'
  package:
    name:
      - pidgin
    state: 'absent'

- include_tasks: 'numix.yml'
  when: ansible_os_family == 'Debian'

- include_tasks: 'xfce4.yml'
  when: ansible_os_family == 'Debian'
