---
- name: 'Install core packages'
  package:
    name: '{{ packages_desktop }}'
    state: 'latest'

- name: 'Disable gdm'
  service:
    name: 'gdm'
    enabled: false
    state: 'stopped'

- name: 'Set default display manager to Lightdm'
  become: true
  copy:
    dest: /etc/X11/default-display-manager
    content: '/usr/sbin/lightdm'
    mode: 0644

- name: 'Reconfigure display manager'
  debconf:
    name: 'lightdm'

- name: 'Enable lightdm'
  service:
    name: 'lightdm'
    enabled: true
    state: 'started'

- name: 'Remove specific desktop packages'
  package:
    name:
      - pidgin
    state: 'absent'

- name: 'bash history - set to infinity'
  become: false
  lineinfile:
    path: '$HOME/.bashrc'
    state: 'present'
    regexp: '^HISTSIZE='
    line: 'HISTSIZE=-1'

- name: 'bash history - do not truncate history file'
  become: false
  lineinfile:
    path: '$HOME/.bashrc'
    state: 'present'
    regexp: '^HISTFILESIZE='
    line: 'HISTFILESIZE='

- include_tasks: 'redshift.yml'
  when: ansible_os_family == 'Debian'

- include_tasks: 'numix.yml'
  when: ansible_os_family == 'Debian'

- include_tasks: 'xfce4.yml'
  when: ansible_os_family == 'Debian'

- include_tasks: 'fzf.yml'
  when: ansible_os_family == 'Debian'
