---
# install Numix GTK theme, part of the Numix Project http://numixproject.org
- name: 'numix - add PPA repo'
  apt_repository:
    repo: 'ppa:numix/ppa'
    state: 'present'
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: 'numix - install'
  package:
    name: 'numix-gtk-theme'
    state: 'latest'
  when: ansible_os_family == 'Debian'

- name: 'numix - set as default'
  become: false
  # become_user: kaszpir
  # become_method: su
  shell: |
    whoami
    eval `dbus-launch --sh-syntax`
    xfconf-query -c xsettings -p /Net/ThemeName -s "Numix"
    xfconf-query -n -c xfwm4 -p /general/theme -s "Numix" -t string
    kill -HUP $DBUS_SESSION_BUS_PID
  args:
    executable: /bin/bash
  when: ansible_os_family == 'Debian'
