---
# install redshift for xfce
- name: 'redshift - add PPA repo'
  apt_repository:
    repo: 'ppa:dobey/redshift-daily'
    state: 'present'
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: 'redshift - install'
  package:
    name:
      - redshift
      - redshift-gtk
    state: 'latest'
  when: ansible_os_family == 'Debian'

# todo, config template?
