---
- name: 'doublecmd - add PPA repo'
  apt_repository:
    repo: 'ppa:alexx2000/doublecmd'
    state: 'present'
    update_cache: true
  when:
    - ansible_os_family == 'Debian'
    - (ansible_distribution_major_version| int) < 20

# switch to qt version, gtk sometimes has some weird
# delays with simple things like renaming file
- name: 'doublecmd - install'
  package:
    name: 'doublecmd-qt'
    state: 'latest'
  when: ansible_os_family == 'Debian'
