---
# fuzzy find
# https://github.com/junegunn/fzf#using-git
- name: 'fuzzyfind - clone'
  become: false
  # become_user: kaszpir
  # become_method: su
  git:
    depth: 1
    clone: true
    dest: "$HOME/.fzf"
    repo: 'https://github.com/junegunn/fzf.git'
    force: true
    version: 0.18.0
  when: ansible_os_family == 'Debian'

- name: 'fuzzyfind - install'
  become: false
  shell:
    $HOME/.fzf/install --all --no-zsh --no-fish
  args:
    executable: /bin/bash
  when: ansible_os_family == 'Debian'
  tags:
    - skip_ansible_lint
